name: cspy2
channels:
- defaults
dependencies:
- openssl=1.0.2l=0
- pip=9.0.1=py27_1
- python=2.7.13=0
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - appnope==0.1.0
  - backports.shutil-get-terminal-size==1.0.0
  - beautifulsoup4==4.6.0
  - certifi==2017.4.17
  - cffi==1.11.0
  - chardet==3.0.4
  - crypto==1.4.1
  - decorator==4.0.11
  - enum34==1.1.6
  - faker==0.7.17
  - gevent==1.2.2
  - greenlet==0.4.12
  - idna==2.5
  - ipaddress==1.0.18
  - ipython==5.4.1
  - ipython-genutils==0.2.0
  - itsdangerous==0.24
  - misaka==2.1.0
  - naked==0.1.31
  - olefile==0.44
  - pathlib2==2.3.0
  - peewee==2.10.1
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - pillow==4.3.0
  - profilehooks==1.9.0
  - prompt-toolkit==1.0.14
  - ptyprocess==0.5.2
  - pycparser==2.18
  - pygments==2.2.0
  - pymysql==0.7.11
  - python-dateutil==2.6.0
  - pyyaml==3.12
  - qiniu==7.2.0
  - redis==2.10.5
  - requests==2.18.1
  - scandir==1.5
  - schematics==2.0.1
  - shellescape==3.4.1
  - simplegeneric==0.8.1
  - simplejson==3.11.1
  - six==1.10.0
  - statsd==3.2.1
  - traitlets==4.3.2
  - urllib3==1.21.1
  - wcwidth==0.1.7

